version: '4.0.0'

services:
  instockdbservice:
    image: library/mariadb:latest
    container_name: InStockDbService
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /data/mariadb/data:/var/lib/instockdb
    networks:
      - instock_network

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: InStockClickHouse
    hostname: clickhouse
    ports:
      - "8123:8123"  # HTTP接口
      - "9000:9000"  # Native接口
    environment:
      CLICKHOUSE_DB: instockdb
      CLICKHOUSE_USER: root
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      CLICKHOUSE_PASSWORD: 123456
    volumes:
      - /data/clickhouse/data:/var/lib/clickhouse
      - /data/clickhouse/logs:/var/log/clickhouse-server
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - instock_network
    restart: unless-stopped

  instock:
    image: mayanghua/instock:latest
    container_name: InStock
    ports:
      - "9988:9988"
    environment:
      db_host: InStockDbService
      clickhouse_host: clickhouse
      CLICKHOUSE_PASSWORD: 123456
    depends_on:
      - instockdbservice
      - clickhouse
    networks:
      - instock_network

networks:
  instock_network:
    driver: bridge

